DROP DATABASE IF EXISTS webapp;
CREATE DATABASE webapp;

USE webapp;

CREATE TABLE todos
(
    id INT NOT NULL AUTO_INCREMENT,
    task VARCHAR(255) NOT NULL,
    done BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);